# Doing a Linear regression without Scikit Learn

There's nothing better to understand the gradient descent algorithm than to code it from scratch. It may seem difficult at first glance but don't worry, we will guide you step by step. It is also a fantastic occasion to practice python key concepts like **Classes**!

Don't hesitate to come back to your Machine Learning course on linear regression to refresh your memory. 

Our goal will be to code a simple linear regression such as : 

$f(x) = \beta_1 \times x + \beta_0$

* Import the following libraries: 
  * Numpy 

In [6]:
import numpy as np

* Define a `Model` class that will take two methods: 
  1. `__init__(self)`, the class builder which will allow you to define an attribute $\beta_0$ (`beta_0` in your code) and an attribute $\beta_1$ (`beta_1` in your code). These attributes represent the coefficients/parameters of the model an we will be initialize them randomly using Numpy (cf: `np.random.randn`).
  2. `__call__(self, x)`, a special method that will turn our class into a callable which will return $\beta_1 \times x + \beta_0$ when called.

In [7]:
class Model:

    def __init__(self):
        self.beta_0 = np.random.randn(1)
        self.beta_1 = np.random.randn(1)

    def __call__(self, x):
        return self.beta_1*x + self.beta_0


* Create an instance of your class `Model`

In [9]:
model = Model()

In [10]:
# have a look at the attribute beta_0 (it's a random value)

model.beta_0

array([2.55992537])

In [ ]:
# have a look at the attribute beta_1 (it's a random value)

model.beta_1

array([1.0555889])

* Try doing a first "regression" by running `model(3.0)`.    
NB: If you don't have the same values as this notebook in output, this is normal since you have initialized your values randomly. 

In [ ]:
model(3.0)

array([2.03793218])

* This value corresponds to a random prediction of your model. But we don't have any data yet. This time, let's use `sklearn` to import data. 
  * Import `sklearn.datasets`
  * Use the `load_diabetes()` function to load the diebetes dataset in an object called `diabetes`.
  * Print the `DESCR` attribute of the diabetes object
  * Save the content of the `data` attribute in an object named `diabetes_data`
  * Save the content of the `target` attribute in an object named `y`

In [ ]:
from sklearn.datasets import load_diabetes

diabete = load_diabetes()
print(diabete.DESCR)

diabetes_data = diabete.data
y = diabete.target

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

* We have too much data in this dataset `diabetes_data`, take only the third column of the dataset and store it in a `diabetes_X` variable.

In [ ]:
# Use only one feature

diabetes_X = diabetes_data[:, 2]

* Visualize your data using `plotly`.

In [ ]:
import plotly.express as px

fig = px.scatter(x=diabetes_X, y=y)
fig.show()

* Now we need to define a cost function. For a linear regression, we could use MSE :

`np.mean((model(input) - y)**2)`

  * Create this function which we'll call `mse` (for mean square error). This function will take two arguments `y_pred` & `y_true`.

In [ ]:
def mse(y_pred, y_true):
    return np.mean((y_pred - y_true)**2)

* Test your function by inserting `model(diabetes_X)` & `y` as arguments. 
* Calculate the rmse as well

In [ ]:
y_pred = model(diabetes_X)
res_mse = mse(y_pred, y)
print(f"MSE : {res_mse}")
print(f"RMSE : {res_mse**0.5}")

MSE : 29414.69084519679
RMSE : 171.50711601912263


* Visualize your regression in relation to your points 

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

fig = px.scatter(x=diabetes_X, y=y)
fig.add_trace(go.Scatter(x=diabetes_X, y=y_pred, mode='lines'))
fig.show()

* We're going to need to compute the gradients for our variable `model.beta_1` and our constant `model.beta_0`. To do this, we're going to need to review our derivative formulas. Since we're not here to do math, we're going to give you these formulas. 
  * `derive_model_beta_1 = 2/len(y_pred)*np.sum((x @ (y_pred - y_true)))`
  * `derive_model_beta_0 = 2/len(y_pred)*(np.sum(y_pred - y_true))`

  * Feel free to read this article if you want to know more about the calculation of the derivative: [Gradient Descent Derivation](https://mccormickml.com/2014/03/04/gradient-descent-derivation/)


  * So using the above formulas, code the first function `derivative_mse_beta_1` that will take the arguments: 
    * `x` --> the values for your variable / `y_pred` --> the values predicted by your model / `y_true` --> the values of the target variable


In [2]:
# Calculate model.beta_1's derivate

def derivative_mse_beta_1(x, y_pred, y_true):
    return 2/len(y_pred)*np.sum((x @ (y_pred - y_true)))

* Test you function

In [5]:
derivative_mse_beta_1(diabetes_X, y_pred, y)

NameError: ignored

* So using the above formulas, now code the `derivative_mse_beta_0` function which will take the arguments :
    * `y_pred` --> the values predicted by your model / `y_true` --> the actual values to predict

In [ ]:
# Calculate model.beta_0's derivate

def derivative_mse_beta_0(y_pred, y_true):
    return 2/len(y_pred)*(np.sum(y_pred - y_true))

* Test your function

In [ ]:
derivative_mse_beta_0(y_pred, y)

-306.52463737343436

* We will try to see if we can minimize our cost function using the two gradients above. To update our variables, we need to subtract their respective gradients. Ex: 
  * `param = param - learning_rate * gradient`

  * Set a `learning_rate` to 0.1
  * Try to apply your formula on `model.beta_1` and `model.beta_0`.

In [ ]:
print(f"OLD model.beta_0 = {model.beta_0}")
print(f"OLD model.beta_1 = {model.beta_1}")
print(f"OLD model MSE = {mse(y_pred, y)}")

model.beta_0 -= 0.1 * derivative_mse_beta_0(y_pred, y)
model.beta_1 -= 0.1 * derivative_mse_beta_1(diabetes_X, y_pred, y)
y_pred = model(diabetes_X)

print(f"NEW model.beta_0 = {model.beta_0}")
print(f"NEW model.beta_1 = {model.beta_1}")
print(f"NEW model MSE = {mse(y_pred, y)}")

OLD model.beta_0 = [-1.12883452]
OLD model.beta_1 = [1.0555889]
OLD model MSE = 29414.69084519679
NEW model.beta_0 = [29.52362921]
NEW model.beta_1 = [1.48471997]
NEW model MSE = 20956.687928532487


We see that the values of the two parameters have changed, let's see how it affected the predictions of the model.  
Visualize the data vs the model's predictions.

In [ ]:
fig = px.scatter(x=diabetes_X, y=y)
fig.add_trace(go.Scatter(x=diabetes_X, y=y_pred, mode='lines'))
fig.show()

We notice the predictions got a little closer to our real data
* Recalculate your MSE

In [ ]:
print(f"NEW model MSE = {mse(y_pred, y)}")

NEW model MSE = 20956.687928532487


* Our MSE has dropped a lot! This is good news but the process of gradient descent is iterative. So you'll have to do it several times before arriving at accurate predictions. 
  * By making a loop, try to repeat the process from above 10,000 times. 
  * Display every 1000 epochs: mse, model.beta_1 & model.beta_0 

In [ ]:
# Define learning rate and a number of iterations 

for i in range(0, 10000):
  y_pred = model(diabetes_X)
  model.beta_0 -= 0.1 * derivative_mse_beta_0(y_pred, y)
  model.beta_1 -= 0.1 * derivative_mse_beta_1(diabetes_X, y_pred, y)
  loss = mse(y_pred, y)
  if not i % 1000:
    print(f"Epoch {i}".center(20, "-"))
    print(f"Current Loss: {loss}")
    print(f"beta_0 = {model.beta_0}")
    print(f"beta_1 = {model.beta_1}")

------Epoch 0-------
Current Loss: 20956.687928532487
beta_0 = [54.0456002]
beta_1 = [1.91365687]
-----Epoch 1000-----
Current Loss: 4712.762587653004
beta_0 = [152.13348416]
beta_1 = [346.83223601]
-----Epoch 2000-----
Current Loss: 4223.053206628629
beta_0 = [152.13348416]
beta_1 = [566.19291146]
-----Epoch 3000-----
Current Loss: 4024.981339162568
beta_0 = [152.13348416]
beta_1 = [705.70150522]
-----Epoch 4000-----
Current Loss: 3944.867569237589
beta_0 = [152.13348416]
beta_1 = [794.4259208]
-----Epoch 5000-----
Current Loss: 3912.464097640631
beta_0 = [152.13348416]
beta_1 = [850.85270934]
-----Epoch 6000-----
Current Loss: 3899.3579241012
beta_0 = [152.13348416]
beta_1 = [886.73891321]
-----Epoch 7000-----
Current Loss: 3894.0568937985763
beta_0 = [152.13348416]
beta_1 = [909.5617543]
-----Epoch 8000-----
Current Loss: 3891.9127956615584
beta_0 = [152.13348416]
beta_1 = [924.07658226]
-----Epoch 9000-----
Current Loss: 3891.04557616672
beta_0 = [152.13348416]
beta_1 = [933.307695

* Using `plotly`, view your model and actual values again

In [ ]:
fig = px.scatter(x=diabetes_X, y=y)
fig.add_trace(go.Scatter(x=diabetes_X, y=y_pred, mode='lines'))
fig.show()

**We've got a nice regression this time!** 