# Translations 
We'll see that with LSTMs, we can do some pretty powerful things like: *translators* ! Let's see how we can create a French > English translator with TensorFlow   

## Project description 
This is not an easy project. This is why we are going to enlighten you on the main steps to follow. 

In [ ]:
# Loading spacy's French and English languages 

In [ ]:
# Import necessaries librairies

'2.4.1'

### Importing data 

First, you will have a `.txt` file containing a sentence with its translation separated by a tab (`\t`). You will then have to import this data and read it via `pandas` or `numpy`. 

Your data can be found on this link: https://go.aws/38ECHUB

**Tips:**   
Don't take the whole dataset at the beginning for your experiments, just take 5000 or even 3000 sentences. This will allow you to iterate faster and avoid bugs simply related to your need for computing power.  

In [ ]:
# Loading document txt

0           1
0   Go.        Va !
1   Hi.     Salut !
2  Run!     Cours !
3  Run!    Courez !
4  Wow!  Ça alors !

(160538, 2)

In [ ]:
# Let's just take a sample of 5000 sentences to avoid slowness. 

In [ ]:
# Loading of the entire corpus of French and English sentences

### Preprocessing 

The whole purpose of your preprocessing is to express your (French) entry sentence in a sequence of clues.

i.e. :

* I'm sick ---> $[123, 21, 34, 0, 0, 0, 0, 0]$

This gives a *shape* -> `(batch_size, max_len_of_a_sentence)`.

The clues correspond to a number that you will have to assign for each word token. 

The zeros correspond to what are called [*padded_sequences*](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences) which allow all word sequences to have the same length (mandatory for your algorithm). 

The transformation of your target sentence will not be exactly the same as that of your input sentence. In addition to all the steps you will have performed for the input sentences, you will also have to *categorize* your target sentence. In other words, an example tensor would look like : 

* I am sick ---> $\begin{bmatrix} 1&0&0&...&0&0 \\ 0&0&0&...&1&0 \\ ... \\ 0&1&0&...&0&0 \end{bmatrix}$

This gives a *shape* -> `(batch_size, max_len_of_an_english_sentence, num_of_classes)`.

To help do this, you can use : 

* `Pandas` or `Numpy` for reading the text file.
* `Spacy` for Tokenization 
* `Tensorflow` for [padded_sequence](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences) & [categorization](https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical?hl=en)

In [ ]:
# Loading both corpora into spacy 

In [ ]:
# Tokenization of each sentence via spacy 

0  ...                                  en_tokens
91947  You needn't have taken a taxi.  ...  (You, need, n't, have, taken, a, taxi, .)
72924     We already know each other.  ...        (We, already, know, each, other, .)
62770      I don't know how to do it.  ...     (I, do, n't, know, how, to, do, it, .)
47901         What a stupid question!  ...             (What, a, stupid, question, !)
36813           You're very talented.  ...              (You, 're, very, talented, .)

[5 rows x 4 columns]

In [ ]:
# Creation of a set() that will take all the unique tokens from our text corpus

3516


In [ ]:
# Same thing for French

4893


In [ ]:
# Creation of an id for each token

In [ ]:
# Creation of functions that will create a vector of indices for each of the token sequences

In [ ]:
# Transformation of tokens into indices

0  ...                                         en_indices
91947  You needn't have taken a taxi.  ...      [1104, 3189, 2248, 1785, 1646, 1009, 34, 242]
72924     We already know each other.  ...                [3109, 1746, 2526, 2849, 2816, 242]
62770      I don't know how to do it.  ...  [1638, 3364, 2248, 2526, 1221, 561, 3364, 2408...
47901         What a stupid question!  ...                        [3496, 1009, 2016, 8, 2862]
36813           You're very talented.  ...                         [1104, 743, 340, 337, 242]

[5 rows x 6 columns]

In [ ]:
# Use of Keras to create token sequences of the same length

In [ ]:
tf.keras.preprocessing.sequence.pad_sequences?

In [ ]:
# Visualization of the shape of one of the tensors

(5000, 30)

In [ ]:
# Visualization of the shape of the other tensor

(5000, 28)

**RQ:** the maximum length of the english sentences (38) is different from the maximum length of the french sentences (29).

28

In [ ]:
# Application of the categorization of the target variable 

(5000, 28, 3517)

In [ ]:
# Creation of tf.data.Dataset for each of the French and English tensors

In [ ]:
# Create a tensorflow dataset complet

In [ ]:
next(iter(tf_ds))

(<tf.Tensor: shape=(30,), dtype=int32, numpy=
 array([ 561,  219,  578, 2693, 3214, 3532, 2245, 1547, 1830, 2265,  330,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)>,
 <tf.Tensor: shape=(28, 3517), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>)

In [ ]:
# Shuffle & Batch

In [ ]:
# Train Test Split

### Modeling 

Once you have that, you can move on to modeling. To create your model, you'll need : 

* A layer of [Embedding](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding?hl=en)
* Layer [LSTM](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM?hl=en) & [Bidirectional](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional?hl=en)
* A layer [RepeatVector](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RepeatVector?hl=en)
* A [Dense](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense?hl=en) & [TimeDistributed](https://www.tensorflow.org/api_docs/python/tf/keras/layers/TimeDistributed?hl=en) output layer

The objective being to have in input, a tensor of dimension `(batch_size, max_len_of_french_sentences)` and in output a tensor of dimension `(batch_size, max_len_of_english_sentences, num_of_classes)` where obviously `max_len_of_english_sentences` $\neq $ `max_len_of_french_sentences`.

In [ ]:
tf.keras.layers.Embedding?

In [ ]:
tf.keras.layers.LSTM?

In [ ]:
tf.keras.layers.Bidirectional?

In [ ]:
# Create the model
model = tf.keras.Sequential([
                  # Input Word Embedding layer

                  # LSTM Bidirectional layer
                  
                  # LSTM Bidirectionnal new layer

                  # Repeat Vector

                  # LSTM new layer               

                  # Output layer with number of output neurons equal to class number with softmax function
           
])

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 30, 64)            313216    
_________________________________________________________________
bidirectional_2 (Bidirection (None, 30, 128)           66048     
_________________________________________________________________
bidirectional_3 (Bidirection (None, 128)               98816     
_________________________________________________________________
repeat_vector_1 (RepeatVecto (None, 28, 128)           0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 28, 32)            20608     
_________________________________________________________________
time_distributed_1 (TimeDist (None, 28, 3517)          116061    
Total params: 614,749
Trainable params: 614,749
Non-trainable params: 0
________________________________________________

In [ ]:
# "Random" prediction to test our model 
input_text, output_text = next(iter(train_data))
print(input_text.numpy().shape)
print(model.predict(input_text).shape)
print(output_text.numpy().shape)

(32, 30)
(32, 28, 3517)
(32, 28, 3517)


In [ ]:
# Let's create a learning rate schedule to decrease the learning rate as we train the model

# Using a simple compiler with an Adam optimizer to compute our gradients

In [ ]:
# Application of the model on 200 epochs

Epoch 1/200
109/109 [==============================] - 34s 150ms/step - loss: 6.7411 - categorical_accuracy: 0.6963 - val_loss: 2.7289 - val_categorical_accuracy: 0.7296
Epoch 2/200
109/109 [==============================] - 10s 90ms/step - loss: 2.3932 - categorical_accuracy: 0.7311 - val_loss: 2.1000 - val_categorical_accuracy: 0.7304
Epoch 3/200
109/109 [==============================] - 10s 90ms/step - loss: 2.0475 - categorical_accuracy: 0.7297 - val_loss: 1.8720 - val_categorical_accuracy: 0.7311
Epoch 4/200
109/109 [==============================] - 10s 90ms/step - loss: 1.8464 - categorical_accuracy: 0.7296 - val_loss: 1.7679 - val_categorical_accuracy: 0.7284
Epoch 5/200
109/109 [==============================] - 10s 89ms/step - loss: 1.7364 - categorical_accuracy: 0.7310 - val_loss: 1.6681 - val_categorical_accuracy: 0.7370
Epoch 6/200
109/109 [==============================] - 10s 90ms/step - loss: 1.6716 - categorical_accuracy: 0.7380 - val_loss: 1.6422 - val_categorical_ac

In [ ]:
# Testing a translation

In [ ]:
# create a dictionnary with index as keys and word as values

In [ ]:
# French Sentence

Que
veux
-
tu
dire
 
?


In [ ]:
# Real English Sentence 

What
do
you
mean
?


In [ ]:
# Sentence translated into English by the model 

How
did
you
you
?


In [ ]:
# Training on 500 more epochs

Epoch 1/500
109/109 [==============================] - 11s 91ms/step - loss: 0.8054 - categorical_accuracy: 0.8418 - val_loss: 0.7867 - val_categorical_accuracy: 0.8459
Epoch 2/500
109/109 [==============================] - 11s 95ms/step - loss: 0.8004 - categorical_accuracy: 0.8426 - val_loss: 0.8038 - val_categorical_accuracy: 0.8425
Epoch 3/500
109/109 [==============================] - 11s 94ms/step - loss: 0.7981 - categorical_accuracy: 0.8434 - val_loss: 0.7952 - val_categorical_accuracy: 0.8435
Epoch 4/500
109/109 [==============================] - 11s 92ms/step - loss: 0.7999 - categorical_accuracy: 0.8429 - val_loss: 0.7954 - val_categorical_accuracy: 0.8436
Epoch 5/500
109/109 [==============================] - 11s 91ms/step - loss: 0.8016 - categorical_accuracy: 0.8419 - val_loss: 0.8080 - val_categorical_accuracy: 0.8413
Epoch 6/500
109/109 [==============================] - 10s 89ms/step - loss: 0.8038 - categorical_accuracy: 0.8417 - val_loss: 0.7943 - val_categorical_acc

In [ ]:
# Testing on new translations

# French

# True

# Pred

Input Sentence: Tom aurait pu protéger Mary . 
True Translation: Tom could 've protected Mary . 
Model Translation: Tom 're not protected Mary . 